# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 30

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
daysUntilClose: 7

# Only issues or pull requests with all of these labels are considered by StaleBot. Defaults to `[]` (disabled)
onlyLabels:
  - 'needs more info'

# Ignore issues in projects
exemptProjects: true

# Ignore issues and PRs in milestones
exemptMilestones: true

# Set to true to ignore issues with an assignee
exemptAssignees: true

# Label to use when marking as stale
staleLabel: closed:stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. If you have not received a response for our team (apologies for the delay) and this is still a blocker, please reply with additional information or just a ping. Thank you for your contribution! 🙇‍♂️
