language: node_js
node_js:
- '6.9.1'
script:
- 'npm run test:cli'
- 'npm run test:jest'
env:
  - CXX=g++-4.8
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
  - master
cache:
  directories:
    - node_modules
notifications:
  slack:
    secure: YAMGxva36BTZpSSBwzMqPbZ+2GEZTYbuQd607vSB6AEbEbDLxGmW5bwbUFbWs+jGsfutSDQJykgeFMz/kAV92iUJbG2jYsPlodjVec+Y6neVeAsHV7LgWnVm2mTcJVBODZQlAZvwxT971UuWu54SbJP3yg/IKiEWYdB8pZiTMfI=
