ui: mocha-bdd
tunnel:
  type: ngrok
  authtoken: LsVZFxFqgxA4h7ibWV9V_iuA9afbQwaSnGqH9dApL
scripts:
  - "/node_modules/jquery/dist/jquery.min.js"
  - "/node_modules/expect.js/expect.js"
  - "/node_modules/bean/bean.min.js"
  - "/build/auth0-lock.js"
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
