export default {
  Events: {
    CHANGE: 'CHANGE'
  },

  ActionTypes: {
    CHANGE_EMAIL: 'CHANGE_EMAIL',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    INPUT_EMAIL: 'INPUT_EMAIL',
    INPUT_PASSWORD: 'INPUT_PASSWORD',
    FAILED_SIGN_IN: 'FAILED_SIGN_IN',
    HIDE_LOCK: 'HIDE_LOCK',
    INVALIDATE_CREDENTIALS: 'INVALIDATE_CREDENTIALS',
    RECEIVE_CLIENT: 'RECEIVE_CLIENT',
    RECEIVE_CLIENT_ERROR: 'RECEIVE_CLIENT_ERROR',
    RECEIVE_CLIENT_TIMEOUT: 'RECEIVE_CLIENT_TIMEOUT',
    RECEIVE_GRAVATAR_DISPLAY_NAME: 'RECEIVE_GRAVATAR_DISPLAY_NAME',
    RECEIVE_GRAVATAR_DISPLAY_NAME_ERROR: 'RECEIVE_GRAVATAR_DISPLAY_NAME_ERROR',
    RECEIVE_GRAVATAR_IMAGE: 'RECEIVE_GRAVATAR_IMAGE',
    RECEIVE_GRAVATAR_IMAGE_ERROR: 'RECEIVE_GRAVATAR_IMAGE_ERROR',
    SETUP_LOCK: 'SETUP_LOCK',
    SHOW_LOCK: 'SHOW_LOCK',
    SIGN_IN: 'SIGN_IN',
    SUCCESSFUL_SIGN_IN: 'SUCCESSFUL_SIGN_IN'
  },

  LockModes: {
    CRASHED: 'CRASHED',
    LOADING: 'LOADING',
    SIGN_IN: 'SIGN_IN',
    PASSWORDLESS_EMAIL: 'PASSWORDLESS_EMAIL',
    PASSWORDLESS_SMS: 'PASSWORDLESS_SMS'
  },

  LockStates: {
    CRASHED: 'CRASHED',
    FAILED_SIGN_IN: 'FAILED_SIGN_IN',
    READY: 'READY',
    SIGNED_IN: 'SIGNED_IN',
    SIGNING_IN: 'SIGNING_IN',
    WAITING_CLIENT_CONFIG: 'WAITING_CLIENT_CONFIG'
  }
}
