version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:14.15
    environment:
          LANG: en_US.UTF-8
    context:
      - browserstack-env
    steps:
      - checkout
      - run: 
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore-cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name: Build
          command: yarn build
      - run: 
          name: Unit Tests
          command: yarn test
      - run:
          name: Browser Tests
          command: yarn test:e2e:browserstack
      - store_artifacts:
          path: build

workflows:
  version: 2
  build-test-report:
    jobs:
      - build-and-test